global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 60s
  external_labels:
    prom_type: last_mile

scrape_configs:
  - job_name: example
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - 172.17.0.1:6060
